// mockData.js
export const mockUsers = [
  {
    id: "u1",
    fullName: "Amaka Obi",
    email: "amaka@example.com",
    role: "volunteer",
    createdAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "u2",
    fullName: "Lagos Food Bank Initiative",
    email: "contact@lagosfoodbank.org",
    role: "organizer",
    cacNumber: "RC1234567",
    cacVerified: true,
    createdAt: "2026-08-03T09:30:00.000Z",
  },
  {
    id: "u3",
    fullName: "Tunde Bakare",
    email: "tunde@example.com",
    role: "volunteer",
    createdAt: "2026-08-10T14:20:00.000Z",
  },
  {
    id: "u4",
    fullName: "Bridge Scholars Project",
    email: "contact@bridgescholars.org",
    role: "organizer",
    cacNumber: "RC7654321",
    cacVerified: true,
    createdAt: "2026-08-12T09:00:00.000Z",
  },
  {
    id: "u5",
    fullName: "Clean Earth Hub",
    email: "contact@cleanearthhub.org",
    role: "organizer",
    cacNumber: "RC9988776",
    cacVerified: false,
    createdAt: "2026-09-01T09:00:00.000Z",
  },
  {
    id: "u-admin-1",
    fullName: "Haven 87 Admin",
    email: "admin@haven87.app",
    role: "admin",
    createdAt: "2025-01-01T00:00:00.000Z",
  },
];

export const mockOpportunities = [
  {
    id: "o1",
    title: "Weekend Community Kitchen Prep",
    description: "Help prep and pack meals for weekend distribution.",
    category: "Food Relief",
    location: "Ikeja, Lagos",
    date: "2026-10-10",
    schedule: "Saturdays, 8:00 AM – 1:00 PM",
    tagline: "Meal pack & logistics",
    organizerId: "u2",
    totalSpots: 20,
    createdAt: "2026-09-01T08:00:00.000Z",
  },
  {
    id: "o2",
    title: "After-School Math & Reading Mentor",
    description: "Support underprivileged kids with weekend reading and math sessions.",
    category: "Youth & Literacy",
    location: "Yaba, Lagos",
    date: "2026-10-14",
    schedule: "2 weekdays/week, 3:30 PM – 5:30 PM",
    tagline: "Primary tutoring",
    organizerId: "u4",
    totalSpots: 10,
    createdAt: "2026-09-05T11:15:00.000Z",
  },
  {
    id: "o3",
    title: "Urban Wetland Tree Planting & Cleanup",
    description: "Join a hands-on conservation day planting trees and clearing waste.",
    category: "Environmental Action",
    location: "Jabi Lake Park, Abuja",
    date: "2026-11-29",
    schedule: "Saturday, Nov 29",
    tagline: "Outdoor conservation",
    organizerId: "u5",
    totalSpots: 20,
    createdAt: "2026-09-10T08:00:00.000Z",
  },
];

export const mockApplications = [
  {
    id: "a1",
    opportunityId: "o1",
    volunteerId: "u1",
    volunteerName: "Amaka Obi",
    status: "approved",
    appliedAt: "2026-09-10T12:00:00.000Z",
  },
  {
    id: "a2",
    opportunityId: "o2",
    volunteerId: "u1",
    volunteerName: "Amaka Obi",
    status: "pending",
    appliedAt: "2026-09-15T09:00:00.000Z",
  },
  {
    id: "a3",
    opportunityId: "o3",
    volunteerId: "u1",
    volunteerName: "Amaka Obi",
    status: "rejected",
    appliedAt: "2026-09-12T14:00:00.000Z",
  },
];
